/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Documents: () => import('#controllers/documents_controller'),
  Favicon: () => import('#controllers/favicon_controller'),
  Index: () => import('#controllers/index_controller'),
  Robots: () => import('#controllers/robots_controller'),
  Search: () => import('#controllers/search_controller'),
  Sitemap: () => import('#controllers/sitemap_controller'),
}
