/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class DocumentCommitSchema extends BaseModel {
  static $columns = ['additions', 'author', 'committedAt', 'createdAt', 'deletions', 'documentId', 'hash', 'id', 'message'] as const
  $columns = DocumentCommitSchema.$columns
  @column()
  declare additions: number
  @column()
  declare author: string
  @column.dateTime()
  declare committedAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare deletions: number
  @column()
  declare documentId: number
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare message: string
}

export class DocumentLinkSchema extends BaseModel {
  static $columns = ['createdAt', 'fromDocumentId', 'id', 'toDocumentId'] as const
  $columns = DocumentLinkSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fromDocumentId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare toDocumentId: number
}

export class DocumentSchema extends BaseModel {
  static $columns = ['commitCount', 'contentHtml', 'contentText', 'createdAt', 'firstCommitAt', 'hash', 'id', 'lastCommitAt', 'number', 'preamble', 'project', 'rawContent', 'sortOrder', 'sourceFormat', 'sourceUrl', 'title', 'toc', 'updatedAt'] as const
  $columns = DocumentSchema.$columns
  @column()
  declare commitCount: number | null
  @column()
  declare contentHtml: string | null
  @column()
  declare contentText: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare firstCommitAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastCommitAt: DateTime | null
  @column()
  declare number: string
  @column()
  declare preamble: string
  @column()
  declare project: string
  @column()
  declare rawContent: string | null
  @column()
  declare sortOrder: number
  @column()
  declare sourceFormat: string
  @column()
  declare sourceUrl: string
  @column()
  declare title: string
  @column()
  declare toc: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProjectMetaSchema extends BaseModel {
  static $columns = ['homeContent', 'homeFormat', 'homeHash', 'homeHtml', 'homeSourceUrl', 'lastUpdate', 'project'] as const
  $columns = ProjectMetaSchema.$columns
  @column()
  declare homeContent: string | null
  @column()
  declare homeFormat: string | null
  @column()
  declare homeHash: string | null
  @column()
  declare homeHtml: string | null
  @column()
  declare homeSourceUrl: string | null
  @column.dateTime()
  declare lastUpdate: DateTime | null
  @column({ isPrimary: true })
  declare project: string
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
